include:
 - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/6a40df92957c8ce9ee741aaccc5daaaf70545b1e/templates/fedora.yml'

variables:
  FDO_UPSTREAM_REPO: GNOME/libsoup

.fedora.container.common:
  variables:
    FDO_DISTRIBUTION_TAG: '2024-09-11.7'
    FDO_DISTRIBUTION_VERSION: 'latest'

build.container.fedora@x86_64:
  extends:
  - '.fdo.container-build@fedora'
  - '.fedora.container.common'
  stage: prepare
  variables:
    GIT_STRATEGY: none
    FDO_EXPIRES_AFTER: 8w
    FDO_DISTRIBUTION_PACKAGES: >-
      brotli-devel
      clang-analyzer
      'dnf-command(builddep)'
      gcovr
      git
      gi-docgen
      glib2-doc
      glib-networking
      gnutls-devel
      gobject-introspection-devel
      gtk-doc
      httpd
      krb5-devel
      lcov
      libasan
      libnghttp2-devel
      libpsl-devel
      libsoup-doc
      lsof
      meson
      mod_http2
      mod_ssl
      python2.7
      redhat-rpm-config
      samba-winbind-clients
      sqlite-devel
      sysprof-devel
      vala
      valgrind
      which
    FDO_DISTRIBUTION_EXEC: >-
      python2.7 -m ensurepip &&
      pip2.7 install --upgrade pip &&
      pip2.7 install virtualenv wsaccel==0.6.3 autobahntestsuite

# FIXME: restore this to disable CI for branch commits
#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#    - if: $CI_COMMIT_TAG
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - prepare
  - build
  - coverage
  - docs
  - deploy

.build:
  stage: build
  tags:
    # We need runners supporting IPv6:
    # https://gitlab.gnome.org/Infrastructure/GitLab/issues/313
    - ipv6

fedora-test:
  extends:
    - '.fdo.distribution-image@fedora'
    - '.fedora.container.common'
    - '.build'
  script:
    - cp .gitlab-ci/lcovrc ~/.lcovrc
    - meson _build -Db_coverage=true --auto-features=enabled
    - meson compile -C _build
    - meson test --no-suite autobahn-quick --no-suite autobahn -C _build --verbose
    - ninja -C _build coverage-html coverage-xml
  artifacts:
    reports:
      junit: "_build/meson-logs/testlog.junit.xml"
      coverage_report:
        coverage_format: cobertura
        path: "_build/meson-logs/coverage.xml"
    name: "libsoup-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "_build/config.h"
      - "_build/meson-logs/meson-log.txt"
      - "_build/meson-logs/testlog.txt"
      - "_build/meson-logs/coveragereport"
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'

fedora-autobahn-quick:
  extends:
    - '.fdo.distribution-image@fedora'
    - '.fedora.container.common'
    - '.build'
  script:
    - meson _build --auto-features=enabled -Dautobahn=enabled
    - meson test -C _build --suite autobahn-quick --verbose
  artifacts:
    paths:
      - "_build/meson-logs/autobahn-report"
  allow_failure: true

fedora-scan:
  extends:
    - '.fdo.distribution-image@fedora'
    - '.fedora.container.common'
    - '.build'
  script:
    - meson _build --auto-features=enabled
    - SCANBUILD=$(pwd)/run-scan-build ninja -C _build scan-build
    - bash -c 'if [[ -n "$(ls -A _build/meson-logs/scanbuild/)" ]]; then echo "Scan build log found, assuming defects exist"; exit 1; fi'
  artifacts:
    reports:
      junit: "_build/meson-logs/testlog.junit.xml"
    when: on_failure
    paths:
      - _build/meson-logs/scanbuild

fedora-asan:
  extends:
    - '.fdo.distribution-image@fedora'
    - '.fedora.container.common'
    - '.build'
  tags:
    - asan
  variables:
    ASAN_OPTIONS: fast_unwind_on_malloc=0
    SOUP_TEST_NO_IPV6: 1
  script:
    # Introspection doesn't work when linking to libasan, the NTLM tests fail most likely due to unsafe usage of setenv()
    - meson _build --auto-features=enabled -Db_sanitize=address -Dintrospection=disabled -Dvapi=disabled -Dntlm=disabled -Ddocs=disabled
    - meson test --no-suite autobahn-quick --no-suite autobahn -C _build --verbose --timeout-multiplier=10
  artifacts:
    reports:
      junit: "_build/meson-logs/testlog.junit.xml"
    when: on_failure
    paths:
      - "_build/meson-logs/testlog.txt"

# fedora-fuzzing:
#  extends:
#    - '.fdo.distribution-image@fedora'
#    - '.fedora.container.common'
#    - '.build'
#   allow_failure: true
#   variables:
#     CC: clang
#   script:
#     - meson _build --auto-features=enabled -Dfuzzing=enabled -Dintrospection=disabled -Dvapi=disabled
#     - meson test -C _build --suite=fuzzing --timeout-multiplier=10
#   artifacts:
#     when: on_failure
#     paths:
#       - _build/meson-logs/

reference:
  extends:
    - '.fdo.distribution-image@fedora'
    - '.fedora.container.common'
  stage: docs
  variables:
    MESON_ARGS: >-
      -Ddocs=enabled
      -Ddoc_tests=true
      -Dvapi=disabled
  script:
    - mkdir -p _reference/libsoup-3.0
    - meson ${MESON_ARGS} _build
    - meson compile -C _build libsoup-doc --verbose
    - meson test -C _build docs --verbose
    - mv _build/docs/reference/libsoup-3.0/* _reference/libsoup-3.0
    # Add libsoup-2.4 docs.
    - cp -R /usr/share/gtk-doc/html/{glib,gio,gobject,libsoup-2.4} _reference/
    - gtkdoc-rebase --relative --html-dir=_reference/{glib,gio,gobject,libsoup-2.4} --verbose
    - cp .gitlab-ci/{index.html,robots.txt} _reference/
  artifacts:
    paths:
      - _reference

pages:
  extends:
    - '.fdo.distribution-image@fedora'
    - '.fedora.container.common'
  stage: deploy
  needs: ['reference']
  script:
    - mv _reference public
  artifacts:
    when: on_success
    paths:
      - public
  only:
    - master
